### ISSUE TITLE
PurgeCSS

### ISSUE THREAD

**Issue by kaisheng1** [GeoffSelby/cra-template-tailwindcss#1]
It's not really an issue but I'm just wondering why you didn't include purgecss as it was claimed to be the best choice to optimise tailwindcss.

**Comment by GeoffSelby** [comment]
Honestly it was a slight oversight on my end. I will add it in the next day or two.

Thanks for bringing it to my attention! 👍

**Comment by GeoffSelby** [comment]
Closed this in fd1aeb2
