### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by matt-d-webb** [GeoffSelby/cra-template-tailwindcss#11]
I am utilising the `@geoffcodesthings/react-scripts` package to run my CRA tailwind project and have recently started seeing the following error running locally:

![image](https://user-images.githubusercontent.com/36933715/146677270-ce90c4f9-d030-4b52-b8e1-9a7ca426b74e.png)

Trying to troubleshoot this, I am finding a lot of solutions suggesting "upgrading to react-scrapts v5.0.0" as a solution, for example: 

- https://github.com/facebook/create-react-app/issues/11771
- https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined

_Note: I am not aware of a specific dependency update recently that has lead to this issue surfacing itself._

Is this an issue you're aware of, or how this maybe resolved within the context of this fork that supports the tailwind postcss plugin.

I am using the following dependency versions:

- postcss v8.2.8
- geoffcodesthings/react-scripts v4.0.1
- tailwindcss v2.2.15

**ref:** https://github.com/chess-centre/platform/blob/master/chess-centre-app/package.json

I have tried to blast my `node_modules` and reinstall the dependency tree, this seemed to fix it (I was seeing this manifesting less frequently), but that seems to be short lived as I am now seeing this frequently.

**Comment by matt-d-webb** [comment]
Just to update this, as updating to `react-scripts` v5 is not easily done if using Tailwind unless you plan to update all your css processing scripts (via craco or directly using postcss npm scripts).

A workaround that _seems_ to be working is to add the following to your dev dependency: `"react-error-overlay": "6.0.9"`

Ref: https://github.com/facebook/create-react-app/issues/11771

**Comment by GeoffSelby** [comment]
I will take a look at this after lunch. I’ll need to look into `react-scripts` v5 to see what’s new as well.

**Comment by matt-d-webb** [comment]
I think I was premature in my workaround, I am still seeing this issue. Don't suppose you have managed to dig into what is causing this?

**Comment by GeoffSelby** [comment]
I've been super busy and honestly forgot about this template for a while. My `react-scripts` fork is no longer needed as CRA now supports PostCss 8 and custom a `postcss.config.js`. I just tagged v4 of this template which updates to Tailwind v3 and no longer relies on a custom `react-scripts`.

**Comment by Shrest032** [comment]
Edit: The issue is fixed

@GeoffSelby @matt-d-webb  Are you guys able to fix it because i am still getting this recently i upgrade my webpack v4 to v5 and node version 16 to 20 after that i started getting this issue.
I have already added the "react-error-overlay": "6.0.9", in resolutions and dependencies tried with react-script as well but nothing worked for me also in the webpack documentation from v4 to v5 it was mentioned to use DefinePlugin which i am using already
but still the same.
