### ISSUE TITLE
Require upgrade and correct some warning

### ISSUE THREAD

**Issue by sahilpurav** [GeoffSelby/cra-template-tailwindcss#7]
**I'm getting a warning when using this setup:**

```
Root-level `dependencies` and `scripts` keys in `template.json` are deprecated.
This template should be updated to use the new `package` key.
```

Following packages should be upgraded:

```
@testing-library/react   10.4.9  =>  11.2.2 
autoprefixer              9.8.6   =>  10.0.2
tailwindcss               1.9.6   =>   2.0.1
```

It would be better if we adjust the template as per the latest CRA setup. For that,

- Remove serviceWorker.js setup
- Add support for webvitals.js
- Remove `import React from 'react'` as it is no longer needed when not explicitly used.

**Comment by GeoffSelby** [comment]
I won't be able to update `tailwindcss` or `autoprefixer` until CRA is updated to use Postcss 8. I'll make the other changes later today.

**Comment by sahilpurav** [comment]
@GeoffSelby  - I just made the work for you. Pull request is raised. Please go through it and merge it. Let me know in case you need any more changes.

I have followed the recommended [guidelines by tailwindcss](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build). Once CRA updates its core with PostCSS 8, We can make a new release.

Kindly link the following [pull request](https://github.com/GeoffSelby/cra-template-tailwindcss/pull/8) with this issue.

**Comment by sahilpurav** [comment]
Thanks, @GeoffSelby  but using a custom react-script is not something which I'm looking for as I will not be able to get the regular updates from CRA package. I will create my own version of this package. Thanks again!
